#include<iostream>
#include<vector>
using namespace std;
char t[][5] = { " ", ".+@$", "abc", "def", "ghi", "jkl" , "mno", "pqrs" , "tuv", "wxyz" };
void pro(char n[],int index,char output[],int cindex)
{
    if(n[index]=='\0')
    {
        cout<<output<<endl;
    }
    if(n[index]=='0')
    {
        output[cindex]=32;
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='2')
    {
        output[cindex]='a';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='b';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='c';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='1')
    {
        output[cindex]='.';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='+';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='@';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='$';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='3')
    {
        output[cindex]='d';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='e';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='f';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='4')
    {
        output[cindex]='g';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='h';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='i';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='5')
    {
        output[cindex]='j';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='k';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='l';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='6')
    {
        output[cindex]='m';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='n';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='o';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='7')
    {
        output[cindex]='p';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='q';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='r';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='s';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='8')
    {
        output[cindex]='t';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='u';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='v';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
    if(n[index]=='9')
    {
        output[cindex]='w';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='x';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='y';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
        output[cindex]='z';
        output[cindex+1]='\0';
        pro(n,index+1,output,cindex+1);
    }
}
int main()
{
    char output[11];
    char n[11],i;
    cin.getline(n,10);
    pro(n,0,output,0);
}
